[package]
name = "semaphore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.4", default-features = false, features = ["rand"] }
semaphore = { git = "https://github.com/worldcoin/semaphore-rs" }
